### ISSUE TITLE
Config file, save games

### ISSUE THREAD

**Issue by sn1ce** [jammsen/docker-the-forest-dedicated-server#10]
Hi there,

first of all, thanks for your effort creating this.

I tried this out yesterday, played like 4h with my friends, and i tested to reconnect.
Started in the plane again...

I followed your readme, inserted my serverSteamAccount into the config file.
I also enabled "vac", looked into the logs - was enabled.

Any idea, why it's not saving?
Also changed "autosave" to 5 minutes.

If you can help me, i want you to provide my docker-compose of course :-) 

Many thanks!

**Comment by jammsen** [comment]
Hey @sn1ce 
can you please restart your server and see if the content is back again?
I had this happen to, after like 8 hours buildings vanished, dunno why, never found a reason of log entry.
Maybe i could ask around other Docker-Contributor, if they know a fix.

**Comment by jammsen** [comment]
I asked 2 people i highly respect for their work, maybe they know a fix to this. 
If we really cant fix my version, i have no doubt you are in good hands by both of them.

**Comment by sn1ce** [comment]
Hi, thanks for your answer.

Maybe to get it a bit more detailed - I was after reconnecting at the beginning (on the plane), my friend was still in our Base, and also i could see the Base etc.

Just my Inventory was completely gone.
Yes I already restarted the server.

Any other ideas?

Maybe some prerequisites for the server, that iam missing?

thanks alot.

**Comment by jammsen** [comment]
Hmmm .... Did you save on the base before that?
Also did you click continue on the server browser instead of join? 
Because clicking "continue" gets your "old id" and "old character", just clicking "join" creates a new character and you are fine you can go back to your old save, just disconnect and click continue again, if you overwrite the save, your stuff is gone. Its not that obvious and user friendly tbh.

In the early days there were savegame problems, but it doesnt sound like thats your problem, see: https://steamcommunity.com/app/242760/discussions/1/37470847783644514/

I guess you used my example and did persist your saves in a volume right?

**Comment by sn1ce** [comment]
Ah, thats a good point actually.
I can't remember exactly, if i clicked on "join" or "continue". 
Would make sense now. Let my try it, i will inform you afterwards.

Yes, i created a docker-compose file for it, mounted those two folders to /opt/containers...

Let me check, what happens now, if i click on this "continue" .

**Comment by sn1ce** [comment]
So, iam back - insane ui controlling here...
- search for server - click on "continue" - password etc. AND there are also two buttons - join and continue... Never noticed this before.
And yes - you are completely right with your point **Its not that obvious and user friendly tbh.**

It works "now" - Layer 8 Problem...
Thank you for your help!

**Comment by jammsen** [comment]
Haha, no problem, im happy to help.
