### ISSUE TITLE
Instructions - Overwritten Config

### ISSUE THREAD

**Issue by DiabetoBandito** [jammsen/docker-the-forest-dedicated-server#14]
Hello,

I am attempting to start a server and place my info in the config file. But whenever I start the server, everything gets overwritten in the -v directories. 

Getting Started:
1.Create a new game server account over at https://steamcommunity.com/dev/managegameservers (Use AppID: 242760)
2. **Insert the Login Token in the config (At serverSteamAccount)**
3.  Create 2 directories on your Dockernode (/srv/tfds/steamcmd and /srv/tfds/game)
4. Start the container with the following examples:

Could you elaborate on #2 and #3 of the above instructions?

Thank you,

**Comment by jammsen** [comment]
Hello,
did you go on to the url mentioned in 1.)? 
You can create an account with a login-token there ... 
If you want to persist your gamefiles, you can create folders on your Docker Node/Host
Are you familiar with solid Docker Basics?

**Comment by Willowillins** [comment]
My Config was getting overwritten as well, my friend helped me look into it and we found it was looping because it either assumes TheForestDedicatedServer.exe is there or it was having issues downloading.

I went into steam, downloaded the dedicated server for it, put the contents in here \svr\tfsv\game\ and it worked.

**Comment by jammsen** [comment]
I cant relate to that problem i tried it many times in development and just know again, it is working. My hosted server runs since months, never hat this problem, without any more information i cant help you guys out.

**Comment by Willowillins** [comment]
For context, i am using windows, spawning the docker instance from powershell using the Linux sub system in windows (wsl2)

Is this the same for you @jammsen?

**Comment by jammsen** [comment]
No im using Linux (Debian-based), as listed in my README.md. 

I can't even begin to describe where the problem could be in an emulated linux environment with Docker via Hyper-V and WSL1 or 2. Also the performance with Docker, WSL1/2 and Volume-mounts is horrible, might be the biggest problem in there. Even a native Linux VM via Virtual-Box with a dedicated harddisk is way faster.

**Comment by Willowillins** [comment]
No no, perfectly okay and I accept what your saying - this would be where i assume our issues are derived from.

I did however get the server working and it seems to run fine, just wanted to try and help @DiabetoBandito with some information (download the dedicated server from steam and put it in the game folder!) and get to the bottom of this.

Issues are derived from using windows based dockers I assume :)

**Comment by jammsen** [comment]
> Issues are derived from using windows based dockers I assume :)

Ahh, no its a Linux container with Wine, at least my image we talking about here, but Wine can be .... lets say weird  .... hehehe its comes from the fact that it isnt really an emulator which is good in my mind, but more of a compability layer in Linux to use Windows tools, but by doing so, you get the weirdness of some Windows things into Linux, i hope you kinda get my point here hehehe 

I have to get my toes into Docker Windows Containers, just didnt had the time until now and didnt see the need yet.

**Comment by jammsen** [comment]
Can this be closed?

**Comment by twick00** [comment]
FYI, my server configuration is also being overwritten when I start the server. There is a serious lack of instructions, which is causing two issues:
1. There isn't clear instructions about where to put the config file; A single example config is not enough for most people. If nothing else, please update instructions on what to rename the file to and where it should go.
2. In the instructions, "Dockernode" is could mean a number of different things and I suspect none of them are correct. Please elaborate more on what you mean by this.

Anyways, I appreciate the work you have put in for this! 😄

**Comment by twick00** [comment]
I should also note that I am exclusively using docker-compose.

**Comment by twick00** [comment]
Regarding "Dockernode", is it possible you mean docker volume? Thanks

**Comment by jammsen** [comment]
Hello @twick00

below your answers:

Regarding Dockernode
 - A node that runs Docker
 - Could be more clearer describen yeah, if i update something functional, i will update that as well
 - Context: It comes from Docker-Swarm - "Worker nodes are also instances of Docker Engine whose sole purpose is to execute containers."

Regarding Config
 - The "Getting started" explains at 3 - "Create 2 directories on your Docker host** (/srv/tfds/steamcmd and /srv/tfds/game)" - This is where your stuff including config is, you can find it right there and change it. Of course its a recommandtion on paths and i use it that way. YMMW.
 - The only exception to that is when Servermanager checks if the game is installed and it does NOT find a gameserver, then we create the config directory and put in a valid base config, before the game is installed. Thats because sometimes gameserver come with no base config, UNTIL you start the server first, then an error is throw and the base config is generated, so you have to manually interact multiple times and restart the server again and again. Its just to avoid all that hassle - https://github.com/jammsen/docker-the-forest-dedicated-server/blob/master/usr/bin/servermanager.sh#L65-L72 Config variables are in line 5+6

**Comment by 12souza** [comment]
I am new to docker.. so i created directories within the docker but i do not see, nor can i find any installation files..  I was able to get the server running however.. just wanting to change the server name and the config stuff.

Not really sure what "node" means.. i downloaded this as a zip.. uploaded it.. and just ran the docker.. created those directories within the folder that was unzipped.  Little new to dockers

edit: got it.. sorry

**Comment by jammsen** [comment]
Hello @12souza 
please create next time yourself an issue if you need help and dont reuse old issues which are basically closed be inactivity.

Also i already answered what a node is, you just have to read the post above yours. Here is a TLDR; Node =  a system where a service runs, its a cluster computing term. Dockernode/Dockerhost are interchangeable in my mind.

Judging by your edit, i think you already solved your problem yourself, but here is a little nugget to get more comfortable with Docker and Volumes, which are what you want to research and understand. Just read up here https://docs.docker.com/storage/volumes/

Again ... im not trying to be mean or something, but the readme.MD clearly tells you "What you need to run this: Basic understanding of Linux and Docker" so you will have to do your part too, and get involved and learn the tool, what it can, what not and how to use it to reach your goals you want to achieve.

@12souza i hope it works you and i hope i could help
