### ISSUE TITLE
add name change for the ingame server

### ISSUE THREAD

**Issue by MasonColoretti** [jammsen/docker-the-forest-dedicated-server#42]

**Comment by MasonColoretti** [comment]
using the run cmd

**Comment by njakes** [comment]
You can alter the server name in the config file.

**Comment by jammsen** [comment]
Hey @darkhorse7881 

@njakes is right, you can just edit the config ( see https://github.com/jammsen/docker-the-forest-dedicated-server/blob/master/usr/bin/servermanager.sh#L6 ) it gets created on first time setup and should be mounted to your directories. I dont plan to extend the run command or enviroment-vars for any configline you can edit yourself.

**Comment by jammsen** [comment]
@darkhorse7881 If it would be added in the current "install-part" it would an onetime thing (first install) not an everytime thing (which would mean aggregate every setting and merge anything together, which in itself can cause problems, when ENV says X and config says Y, who is more right?), because right now the the IP settings work that way too, see here:
https://github.com/jammsen/docker-the-forest-dedicated-server/blob/master/usr/bin/servermanager.sh#L57-L67

Can you give me more information about your thoughs and the context and wokrings, then just 1 line please?

**Comment by jammsen** [comment]
Sad to hear nothing for improvement of this image, well then i guess i close this.
