### ISSUE TITLE
Restarting at plane when docker container restarts

### ISSUE THREAD

**Issue by njakes** [jammsen/docker-the-forest-dedicated-server#44]
For quite a while things seemed to be working fairly well. I had a base built and was able to continue at that base.  However, after restarting my server/docker container. It loads me at the airplane every time I join after the docker container restarts.  I click continue when joining the server, it starts the intro cinematic, then on plane.  However, it the base still exists and I can run back to it.  My main issue is every time this happens I lose my entire inventory.  

Any ideas?

**Comment by jammsen** [comment]
Looks (well sounds) to me like a gameserver problem which we cant solve, the developer has to, or maybe a token problem with savegame problems. I hope you did the Token Part as describe in the Readme. Try out maybe a new Token or force updating the gameserver.

**Comment by njakes** [comment]
Do you have any idea on how to force update the gameserver? I can also try a new token.  Thank you for the insights, especially since the problem lies outside of your setup.  Wonderful job by the way, thank you for the effort you put into this.

**Comment by jammsen** [comment]
"Do you have any idea on how to force update the gameserver?"
Restarting should do the trick already. 
If thats not working, you could try to remove the "gameserver-files" from the mounted volume for the server, so there is nothing to start BUT you keep your savegame and config. But be very careful with that and make a backup before doing that please.

" I can also try a new token."
👍 

"Thank you for the insights, especially since the problem lies outside of your setup. Wonderful job by the way, thank you for the effort you put into this."
No problem and thanks! It feels like yesterday i started this endeavour but its acutally years *giggles* ❤️

**Comment by njakes** [comment]
I can confirm that the new token solved my problem. In hindsight I remember setting up to servers on two different machines but accidentally using the same token for the initial start on the second machine.  I'm sure this caused some conflicts on steams side.  Things seem to be working good now.

**Comment by jammsen** [comment]
Nice, good to hear that. Issue can be closed?
