### ISSUE TITLE
Are there any plans to support Sons of the Forest when it releases?

### ISSUE THREAD

**Issue by swirle13** [jammsen/docker-the-forest-dedicated-server#46]
Sorry to open an issue as this isn't an issue, but I wanted to know if you had any plans to support Sons of the Forest when it releases?

I'm currently working on my own solution (hosting the forest dedicated server via Cloudformation launching EC2 windows instance(s) with some bundled powershell scripts, which can be used on both local Windows machines and the hosted windows server) and I came across this repository when I wondered if it was possible to implement via docker.

I imagine it would be very minor changes, mostly the app id, the file name, and possibly the server.cfg files.

Thank you for your work on this. I haven't had a chance to use it yet, but it appears to be a very helpful solution, with 100k+ pulls on docker, no less!

**Comment by jammsen** [comment]
Hello @mjohnson159 - No problem at all, very good question.
Short answer:
I had planned to at least try to get it working. 
Long and more complicated answer:
I sadly have no information yet. Meaning, if there will be a dedicated server, if that app is "free" (like it is in 1) or like Farming-Simulator needs a 2nd game-license. What the dedi needs to run (minimum system requirements, GPU-DX-LEVEL), how to get that working in Wine and all that kind of stuff.

If one of you have any information regarding to this, please share it with me, here.

**Comment by ich777** [comment]
@mjohnson159 please see the discussion over [here](https://steamcommunity.com/app/1326470/discussions/0/3772364735642996856/).

You even can't find a AppID on SteamDB for the dedicated server and the game itself isn't even released yet.
..yes I know it will be released today but no one knows more about anything it seems.

**Comment by jammsen** [comment]
@ich777 Hey Christoph thanks for sharing that, i was a bit suprised you answered here :D 
Are you planing to do a docker-version for unraid in your steamcmd repo?

**Comment by ich777** [comment]
@jammsen I was doing my research on launch day because I got many requests about this game and stumbled across this issue and thought I answer here too.

Yes, I have plans for releasing a dedicated server for SoTF but as said above, no one has any information about dedicated servers and if they are even available at launch. The game client is Windows only from what I see on SteamDB so I'm assuming the dedicated server is Windows only too <- if there is any at launch...

I'll guess we will have to wait until the game is released but my hopes for a dedicated server on launch are not that high because there is no indication on SteamDB for a dedicated server yet.

**Comment by jammsen** [comment]
@ich777 "I was doing my research on launch day because I got many requests about this game and stumbled across this issue and thought I answer here too."
Nice, happy to hear that!

"I'll guess we will have to wait until the game is released but my hopes for a dedicated server on launch are not that high because there is no indication on SteamDB for a dedicated server yet."
Yeah i would assume that under "related apps" there would be another ID. Like it is on Version1 of the game.
The Forest:
https://steamdb.info/app/242760/linked/
Sons of the Forest:
https://steamdb.info/app/1326470/linked/ ( Nothing yet, sadly )

**Comment by jammsen** [comment]
@ich777 According to Steam-Communityposts and people on Discord, Endnight Games ist dodging the question/all questions about "dedicated server" since months, no "yes" or "no" or "we working on it", just plain nothing. Im gonna keep this issue open, for sharing information. Feel free to reach out if you find some informations please.

**Comment by ich777** [comment]
@jammsen this was the same for TheForst if you remember. First there was no dedicated server at all, after a few years (I think) they made it possible so that you can rent servers on well know platforms (Gportal,...) and after half a year dedicated private servers where made available.

I think this will be the case here too.
People have to just wait...

**Comment by jammsen** [comment]
@ich777 I remember it only very vague. (Thanks for the reminder) I really hope that something is coming.

**Comment by ich777** [comment]
Surely is, but it will take some time.

I think they are now fixing bugs which are reported by players (and there are a lot from what I see in the Community Hub on Steam) and after everything is running "good enough" they will release a dedicated server, it is even announced on all big platforms where you can rent dedicated game servers.

**Comment by jammsen** [comment]
@ich777 
https://www.gamestar.de/artikel/sons-of-the-forest-update-plan,3390865.html
No 7

**Comment by ich777** [comment]
That's the right decision from the developers since it is better to release a game without a dedicated server and not say too much about when it will be released because at least I think it is better doing it that way than releasing a dedicated server which is plagued by bugs, crashes and maybe destroy your saves (releasing a dedicated server which is basically broken will also lead to some really bad press and reviews).
By doing it that way they can focus on fix bugs, iron out things which are reported from users and after the game is running decent they can release a dedicated server and focus on that.

The dedicated server was also on the roadmap back then when the game wasn't even released and they even said that it will be released not on launch which again is in my opinion the right decision.
So the only thing we can do is patiently wait.

**Comment by jammsen** [comment]
Yeah i agree with you. 

I just hope they are not like the Satisfactory devs, beacuse they tended to dangle the dedi-server in front of your nose everywhere around when i was the context of "buy the game". But when you followed up the roadmap and milestones, it didnt mean anything, the used literally the same words over 3 years again and again and again ("Some mp-bugs left,will be soon here, but also no eta yet"). They literally started after 3 years to search for a developer who could that actually solve the issue, while knowing they lied to thousands and thousands of people. I hate that kind of missleading of the community to grab our money, while beein totally intrasparent.

**Comment by NightDragon1** [comment]
> Satisfactory
For That one, there is a docker image and it just works fine. Just needs some RAM.

**Comment by ich777** [comment]
@NightDragon1 that was not the point from @jammsen.
I also have a container for Satisfactory but there wasn‘t one when it launched.
They promissed one and delayed it that often that the community got really angry until they released it.

**Comment by jammsen** [comment]
> > Satisfactory
> > For That one, there is a docker image and it just works fine. Just needs some RAM.

Yeah @NightDragon1 what @ich777 is accurate, my point (in a nutshell) was basically saying: "Scummy PR and promises, up to the point where the entire community is angry at you and the chat in streams is only about that topic and toxic until they realize oh we need to hire a guy who can actually do that thing we promised and then finally starting to do what you promised.".

**Comment by NightDragon1** [comment]
It's clear to me that it was different in the past. But now, fortunately, there is a container for it. What I want to say is that sometimes it just takes a little pressure and patience. Of course it's annoying when there are multiplayer modes and they can only be played on Windows from a client. On the other hand, it's something else when you have to build a server for something like that and then also have to fix all kinds of bugs there. Sometimes that's just too much for the studios. Forget about the big company behind it, but think about the people in the team. They surely give more than the company pays them.

**Comment by jammsen** [comment]
@NightDragon1 i dont know what you want me to say here .... i started developing 1999, im a developer at heart and do my DevOps stuff just like it ... i always think developers frist .... you dont have to ask me to think about a few poor devs that does 
get paid 38-40h and does over 50 hours a week to get things like private wow servers running and the community happy, ive been there, ive done that.

But thats not the point, most devs cant do anything about bad decisions, management or pr. Of course they do whats called the hero syndrome to help the company succed and almost never get compensated for it, i dont expect that to not happen, but again, if you promise something you have to deliver on that or the community gets really angry at you, you just have to look at Bliizard - Overwatch2 PVE debacle right now.

**Comment by NightDragon1** [comment]
> @NightDragon1 i dont know what you want me to say here .... i started developing 1999, im a developer at heart and do my DevOps stuff just like it ... i always think developers frist .... you dont have to ask me to think about a few poor devs that does get paid 38-40h and does over 50 hours a week to get things like private wow servers running and the community happy, ive been there, ive done that.
> 
> But thats not the point, most devs cant do anything about bad decisions, management or pr. Of course they do whats called the hero syndrome to help the company succed and almost never get compensated for it, i dont expect that to not happen, but again, if you promise something you have to deliver on that or the community gets really angry at you, you just have to look at Bliizard - Overwatch2 PVE debacle right now.

No offense. Just saying that complaining doesn't help, especially once we bought it already... And ... it's still Early Access... A good public road-map would be more helpful to understand the further plans.

**Comment by ghost** [comment]
@jammsen 
Seems to be out now!

SteamDB app id:
https://steamdb.info/app/2465200/

Documentation:
https://steamcommunity.com/sharedfiles/filedetails/?id=2992700419

**Comment by ich777** [comment]
@jammsen if you need inspiration: [Click](https://github.com/ich777/docker-steamcmd-server/tree/sonsoftheforest) 😉 
Already done...

**Comment by jammsen** [comment]
@vp-en Thanks, working on it.
@ich777  How can i help?

**Comment by ich777** [comment]
@jammsen I've already made a container and everything is working, the link was just if you need something. ;)

**Comment by jammsen** [comment]
@ich777 Im so sorry buddy, i already wrote you on Discord, i miss read. My bad 😞 - Thanks for the input ❤️

**Comment by swirle13** [comment]
I'm glad I was beaten to the punch about the release of dedicated servers! I was excited to see the mention ofEndNight's first pass at dedicated servers. Maybe now I can resume my Terraform project for this!

**Comment by jammsen** [comment]
@mjohnson159 @NightDragon1 @ich777 @vp-en 
Server is done, feel free to do a test.
Repo-Url: https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server
Docker-Hub-Image: https://hub.docker.com/r/jammsen/sons-of-the-forest-dedicated-server

**Comment by jammsen** [comment]
Thanks for the help and inputs, you guys rock!
